services:
  airflow-webserver:
    image: apache/airflow:2.6.2
    env_file: ../.env  # Load environment variables from .env file
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST_NAME}/${MAINTENANCE_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=true  # Set to "false" if you don't want example DAGs
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: ["webserver"]

  airflow-scheduler:
    image: apache/airflow:2.6.2
    env_file: ../.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST_NAME}/${MAINTENANCE_DB}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["scheduler"]

volumes:
  postgres-db-volume: {}
