services:
  airflow-webserver:
    build:
      context: .  # The Dockerfile is in the same directory as docker-compose.yml
      dockerfile: Dockerfile
    env_file: ../.env  # Load environment variables from .env file
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST_NAME}/${MAINTENANCE_DB}
      - AIRFLOW__CORE__LOAD_EXAMPLES=true  # Set to "false" if you don't want example DAGs
    volumes:
      - ../airflow:/opt/airflow  # Mount the entire airflow directory to /opt/airflow
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: ["webserver"]

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../.env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST_NAME}/${MAINTENANCE_DB}
    volumes:
      - ../airflow:/opt/airflow  # Mount the entire airflow directory to /opt/airflow
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    command: ["scheduler"]

volumes:
  postgres-db-volume: {}


# use prefect instead of airflow