name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Add EC2 to known_hosts
      run: |
        ssh-keyscan -H 54.176.180.245 >> ~/.ssh/known_hosts

    - name: git Pull
      run: |
        ssh -v ubuntu@54.176.180.245 << 'EOF'
          # Navigate to your app directory
          echo "Navigating to app directory..."
          cd outlook-AI-jobtracker-chrome-extension/
    
          # Pull the latest changes
          echo "Pulling the latest changes from the develop branch..."
          git pull origin develop
    
          # Activate the virtual environment
          echo "Activating virtual environment..."
          source .venv/bin/activate
    
        EOF
